### ISSUE TITLE
텍스트 서머라이즈 문의드립니다.

### ISSUE THREAD

**Issue by sickkal** [kiyoungkim1/LM-kor#3]
문서 길이가 길면 실행이 안되던데 길이 조절을 어떻게 할 수 있나요?
bertshared_summarization.py 이곳에서 수정하나요?

Traceback (most recent call last):
  File "c:/python/글줄이기.py", line 5, in <module>
    summarize(text)
  File "c:\python\LMkor\examples\bertshared_summarization.py", line 21, in __call__
    max_length=max_length
  File "C:\Users\qusdb\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\qusdb\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\generation_utils.py", line 922, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)  
  File "C:\Users\qusdb\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\generation_utils.py", line 417, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(input_ids, return_dict=True, **encoder_kwargs)
  File "C:\Users\qusdb\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\qusdb\AppData\Local\Programs\Python\Python37\lib\site-packages\transformers\models\bert\modeling_bert.py", line 957, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)    
RuntimeError: The expanded size of the tensor (772) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 772].  Tensor sizes: [1, 512]

**Comment by kiyoungkim1** [comment]
현재 최대 길이는 512 token (약 1000글자)입니다.
더 긴 글을 하시려면 따로 모델을 만들어 학습해야 합니다.
